# Generated by Django 2.1.4 on 2018-12-25 21:14

from django.db import migrations, models
import kms_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_secret_value', kms_field.fields.KMSEncryptedField()),
            ],
        ),
    ]
